### ISSUE TITLE
Reevaluate if saving data on root level might be possible

### ISSUE THREAD

**Issue by goldnead** [goldnead/statamic-collapse-fieldtype#3]
By design this field behaves like any other structured field such as a grid or a replicator fieldtype. This means, any saved data will be grouped like this:
```yaml
any_field: "some data"
collapse_field:
  field_inside: "some data"
```

This might not be the intended behavior. I'll have a look into this and reevaluate if this might be a feature that would be possible in future.
