### ISSUE TITLE
Nested Replicator Fields Stuck Loading

### ISSUE THREAD

**Issue by AaronAtkinson** [goldnead/statamic-collapse-fieldtype#7]
When a replicator field is placed inside a collapse field, the replicator contents fail to load when the collapse field is expanded.

I believe this is the same as the grid behavior pointed out in [issue #1](https://github.com/goldnead/statamic-collapse-fieldtype/issues/1)

The set up in the provided image is a single default collapse field, containing a single default replicator, containing a single default input field (by default field I mean, no changes were made after adding the field).

Here is the yaml file for the blueprint in the screenshot:
```
tabs:
  main:
    display: Main
    sections:
      -
        display: 'Collapse Replicator Test'
        fields:
          -
            handle: collapse_field
            field:
              fields:
                -
                  handle: replicator_field
                  field:
                    collapse: false
                    previews: true
                    fullscreen: true
                    sets:
                      new_set_group:
                        display: 'New Set Group'
                        instructions: null
                        icon: null
                        sets:
                          new_set:
                            display: 'New Set'
                            instructions: null
                            icon: null
                            fields:
                              -
                                handle: text_field
                                field:
                                  input_type: text
                                  antlers: false
                                  type: text
                                  display: 'Text Field'
                                  listable: hidden
                                  instructions_position: above
                                  visibility: visible
                                  replicator_preview: true
                                  hide_display: false
                    type: replicator
                    display: 'Replicator Field'
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
              type: collapse
              display: 'Collapse Field'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
```
<img width="690" alt="image" src="https://github.com/goldnead/statamic-collapse-fieldtype/assets/38330431/fae766e9-7d33-4861-80ea-cfb65e3e7a80">
